name = "redirector"
main = "index.html"
account_id = "73457be37ac667ab15a58aac732f9c9b"
workers_dev = false
compatibility_date = "2025-03-02"

# If using a custom domain route:
zone_id = "05b3f429f6f07158e8d730fe097a60e20e7c5"
